nome=input('escreva seu nome:')
sobrenome=input('escreva seu sobrenome:')
idade=int(input('escreva sua idade:'))
telefone=int(input('escreva o numero de telefone:'))
altura=float(input('escreva sua altura:'))
print('Seu nome:',nome)
print('Seu sobrenome:',sobrenome)
print('Sua idade:',idade)
print('Seu telefone',telefone)
print('Sua altura',altura)